## Summary

\label{sec:summary}

This analysis project aims to answer **whether the levels of PM2.5 air pollution in Beijing, China has improved between 2013 and 2017**. To do so, we performed a **difference in medians hypothesis test** between two intervals, `time_A` (March 2013 - February 2015) and `time_B` (March 2015 - February 2017), and concluded that no statistically significant decrease in PM2.5 particulate measurements can be detected.

This result has implications on both the individual level and state level. On the individual front, this result is indeed unfortunate as Beijing is the second largest city, and home to millions of people. They will face the health repercussions of high PM2.5 levels which are harmful for their respiratory system. On the state front, as China strives to become a global leader, it needs to prove that they are capable of upholding a high standard of collective issues, such as public health and climate change. It needs to start at home, to provide a better future for its own people.
