## Introduction

\label{sec:intro}

The objective of this project is to answer the following inferential question: **Does PM2.5 measurement in Beijing, China collected between 2013 and 2017 show any sign of improvement?**

Beijing, China has long struggled with poor air quality, a result of the country's rapid industrialization and its heavy reliance on coal for electricity generation, as well as its growing and increasingly urban middle class [@wang2012air]. This analysis question is important for its timely and has individual and state-level implications. Presently, more than 1 million deaths are recorded in China annually as a result on air pollution. Moreover, the same group of researchers have show that holding current air quality levels and population constant, climate change could increase PM2.5 levels by 3% by 2050, leading to an additional 12,100 deaths just from an increase in PM2.5 levels alone [@hong2019impacts]. In fact, in September 2021, the World Health Organization revised its air quality guidelines to more restrictive levels following the increasingly evident causal relationships between poor air quality and its harmful health consequences on impacted mainly urban communities [@world2021global]. On the state-front, as China strives to become a leading global power, it needs to prove that they fully support the climate change regime and public health regime. Thus, it is in their interest that they work towards reducing the air pollution in the entire country, including Beijing.

We analyse the `Beijing Air Quality` data set, donated to the UC Irvine Machine Learning Repository in 2019 (accessible via [URL](https://archive-beta.ics.uci.edu/ml/datasets/beijing+multi+site+air+quality+data)), which comprises hourly measurement of six air pollutants (including `PM2.5`, `PM10`, `SO2`, `NO2`, `CO`, `O3`) and six meteorological variables spanning from 2013 until 2017 across twelve of its metropolitan data-collecting stations. While the structure of this data set makes it suitable for multi-variate time-series regression analysis, we focus our analysis solely on the readings of the `PM2.5` metric, a form of fine particulate matter that is considered especially harmful for its ability to penetrate deep into the lungs and cause long-lasting damage to the respiratory system [@xing2016impact].

The report for our exploratory data analysis can be found [here](https://github.com/UBC-MDS/DSCI_522_Beijing_Air_Quality/blob/main/src/Beijing_air_quality_EDA.md).
