## Methods

\label{sec:methods}

### Sub Exploratory Questions:

Through Exploratory Data Analysis, we looking into the following sub-questions:

1.  How does the distribution of air quality data observations look like? Are they normally distributed?
2.  If we split the data into sub data sets based on time frames, will there be any overlap in the ranges of the samples?

We answer the main question of this project using the following methodology pipeline. Based on the theoretical assumption that data points across both samples are independent and identically distributed (i.i.d.) when their hourly collected data are distributed over multi-year time span, we performed a hypothesis test to determine whether there is statistical evidence to indicate an improvement in PM2.5 measurements in Beijing between 2013 and 2017. To do so, we implemented a one-tailed hypothesis test to answer to compare these measurements between two equal-interval time intervals (`time_A` and `time_B`), which we state as:

-   Null Hypothesis ($H_0$): There is no statistically significant decrease in median PM2.5 value in Beijing between time_A and time_B (i.e., $median_{PM2.5_{time\_A}} \leq median_{PM2.5_{time\_B}}$) (Point estimate of PM2.5 in time_A is less than and equal to the point estimate of PM2.5 in time_B), and

-   Alternative Hypothesis ($H_A$): There is a statistically significant decrease in median PM2.5 value in Beijing between time_A and time_B ($median_{PM2.5_{time\_A}} \gt median_{PM2.5_{time\_B}}$) (Point estimate of PM2.5 in time_A is greater than the point estimate of PM2.5 in time_B).
